### ISSUE TITLE
any plan to make this work for chrome?

### ISSUE THREAD

**Issue by alexeadem** [Cimbali/toggle-dark-mode#6]
Great extension. Thanks

**Comment by Cimbali** [comment]
No such plans − I don’t even know how what setting to toggle on chrome, and had to [contribute the webextension mechanism to toggle the firefox setting](https://bugzilla.mozilla.org/show_bug.cgi?id=1733461) myself. Chrome at least [haven’t caught up to use the same mechanism](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/overrideContentColorScheme) AFAICT.
