### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by Martzy303** [Cimbali/toggle-dark-mode#7]
Is it possible to set a keyboard shortcut to toggle between the states?

**Comment by Cimbali** [comment]
Yes, from the `about:addons` page you click on the gear icon and in that menu “Manage extension shortcuts”, You should see Toggle Dark Mode in that list, and you can set the shortcut there.

**Comment by Martzy303** [comment]
Thank you, have learned something, had no idea about that shortcuts section.
