### ISSUE TITLE
Default shortcut clashes with Bitwarden autofill

### ISSUE THREAD

**Issue by FormularSumo** [Cimbali/toggle-dark-mode#8]
The default shortcut for Toggle dark mode is CTRL+SHIFT+L which is the same as the Bitwarden extension defaults to for autofill. It's a pretty minor thing but might be worth changing to be different, as Bitwarden is quite a popular extension that users may already have.

**Comment by Cimbali** [comment]
Unfortunately I don’t think there’s much to be done here.

I don’t feel like going over all popular extensions to find a potential unused key combination. I doubt it exists, and even if so, existing extensions can add more shortcuts, other extensions can gain in popularity, etc. It’s never-ending.

One the other hand default shortcuts can be modified by users, and changing defaults now may annoy users who use the default setting.
